
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-5pm-1
owner: ucsb-cs156-f23
repo_name: team03-f23-5pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjcyODkzMDg0","is_bot":false,"login":"haroldmo","name":""},"headRefName":"Harold-Articles-backend","number":62,"title":"Articles - Copied over backend files from team02 for Articles","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-1/pull/62"},{"author":{"id":"MDQ6VXNlcjU1NTU2Mjk2","is_bot":false,"login":"Yashasvi-Vangala","name":"Yashasvi Vangala"},"headRefName":"yv-RecommendationRequest-backend","number":61,"title":"Transferred RecRequests backend files from team02 ","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-1/pull/61"}]
