
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-5pm-1
owner: ucsb-cs156-f23
repo_name: team03-f23-5pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjU1NTU2Mjk2","is_bot":false,"login":"Yashasvi-Vangala","name":"Yashasvi Vangala"},"headRefName":"yv-RecRequest-Fix-boolean","number":110,"title":"Fixed an error with boolean values not showing up in table","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-1/pull/110"},{"author":{"id":"MDQ6VXNlcjg3MDUzNTg3","is_bot":false,"login":"vinsonlinn","name":""},"headRefName":"vl-HelpRequest-mutation","number":109,"title":"VL - fixed mutation coverage tests","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-1/pull/109"}]
